# Generated by Django 3.1.4 on 2020-12-15 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djgapp', '0002_userextension'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextension',
            name='birthday',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
